### ISSUE TITLE
0.18.0 doesn't build with gcc 5.4

### ISSUE THREAD

**Issue by ex1st** [ranisalt/node-argon2#126]
```
> argon2@0.18.0 install /media/data/app/node_modules/argon2
> node-gyp rebuild

make: Entering directory '/media/data/app/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2.o
../src/argon2.cpp: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/argon2.cpp:199:76: error: call of overloaded ‘log2(unsigned int)’ is ambiguous
     setMaxMin("memoryCost", log2(ARGON2_MAX_MEMORY), log2(ARGON2_MIN_MEMORY));
                                                                            ^
In file included from /usr/include/features.h:367:0,
                 from /usr/include/stdint.h:25,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/stdint.h:9,
                 from ../src/argon2.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:144:1: note: candidate: double log2(double)
 __MATHCALL (log2,, (_Mdouble_ __x));
 ^
../src/argon2.cpp:134:20: note: candidate: constexpr uint32_t {anonymous}::log2(uint64_t)
 constexpr uint32_t log2(uint64_t number)
                    ^
argon2.target.mk:106: recipe for target 'Release/obj.target/argon2/src/argon2.o' failed
make: *** [Release/obj.target/argon2/src/argon2.o] Error 1
make: Leaving directory '/media/data/app/node_modules/argon2/build'
```

**Operating system**:
4.4.0-1054-aws Ubuntu 16.04.4

**Node version:**
v8.11.0

**Compiler version:**
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
```

**With GCC 7.2.0 builds fine. Thank you!**

**Comment by ex1st** [comment]
Hello @ranisalt, fix-126 builds successfully!

**Comment by ranisalt** [comment]
Will publish the fix soon

**Comment by ex1st** [comment]
Thank you!
