### PR TITLE
Fixed build issue on OS X

### PR DESCRIPTION
**Pull request by igi2k**
Hi, I don't have gcc installed, just xcode and this addition will fix issue with CXX during npm install.

### CODE REVIEW

**Comment by ranisalt** [comment]
Can you check which is the lowest OSX version that works with this hack? It should work with 10.8 and maybe with 10.7 too.

**Comment by igi2k** [comment]
If I change it to anything lower than 10.9 I'm getting this error:
`../src/argon2_node.cpp:6:10: fatal error: 'tuple' file not found`

**Comment by ranisalt** [comment]
That's weird, but if it works for now I can live with it.
