### ISSUE TITLE
Build fails in argon2_node.cpp on Debian with gcc/cpp 4.9

### ISSUE THREAD

**Issue by apydo** [ranisalt/node-argon2#160]
### Steps to reproduce
1. npm install argon2

### Expected behaviour
No compilation error, works fine with 0.19.3

### Actual behaviour
```
> argon2@0.20.1 install /var/content/nodejs/lapv3dev/node_modules/argon2
> node-gyp rebuild

make: Entering directory '/var/content/nodejs/lapv3dev/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
../src/argon2_node.cpp: In constructor ‘{anonymous}::HashWorker::HashWorker(const Napi::Function&, std::string&&, std::string&&, {anonymous}::Options&&)’:
../src/argon2_node.cpp:78:35: error: cannot convert ‘std::remove_reference<{anonymous}::Options&>::type {aka {anonymous}::Options}’ to ‘uint32_t {aka unsigned int}’ in initialization
         options{std::move(options)}
                                   ^
../src/argon2_node.cpp:78:35: warning: missing initializer for member ‘{anonymous}::Options::time_cost’ [-Wmissing-field-initializers]
../src/argon2_node.cpp:78:35: warning: missing initializer for member ‘{anonymous}::Options::memory_cost’ [-Wmissing-field-initializers]
../src/argon2_node.cpp:78:35: warning: missing initializer for member ‘{anonymous}::Options::parallelism’ [-Wmissing-field-initializers]
../src/argon2_node.cpp:78:35: warning: missing initializer for member ‘{anonymous}::Options::version’ [-Wmissing-field-initializers]
../src/argon2_node.cpp:78:35: warning: missing initializer for member ‘{anonymous}::Options::type’ [-Wmissing-field-initializers]
argon2.target.mk:110: recipe for target 'Release/obj.target/argon2/src/argon2_node.o' failed
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
make: Leaving directory '/var/content/nodejs/lapv3dev/node_modules/argon2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.16.0-7-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/content/nodejs/lapv3dev/node_modules/argon2
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.20.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! Failed at the argon2@0.20.1 install script.
```
### Environment
**Operating system**: Debian 8.11

**Node version:** node 10.15.1 + npm 6.7.0 + node-gyp 3.8.0

**Compiler version:** gcc/cpp 4.9

**Comment by mmikhalko** [comment]
Have the same problem!

**Comment by Anaphase** [comment]
I have the same issue with getting argon2 installed on a CodeShip container (Ubuntu 14.04 / Node 10.11.0 / npm 6.4.1 / gcc 4.8.4) :(

**Comment by ranisalt** [comment]
> I'm thinking that somewhere in the version update history of argon2 the `g++ >= 4.8` requirement changed to `g++ >= 4.9`

Kinda, when the C++ code was refactored for C++11, yes. `gcc < 5` does not handle well some of C++11 syntax, namely bracket initializers, and triggers an error that does not make sense.

**Comment by ranisalt** [comment]
@apydo @mmikhalko @Anaphase is it possible for you to upgrade to GCC >= 5?

**Comment by Anaphase** [comment]
Coincidentally, just two days ago CodeShip started offering build containers with Unbuntu Bionic installed, along with g++ 7, so opting in to that fixed my problems 👍

**Comment by apydo** [comment]
Well, there is no Jessie deb package for g++ 5 in standard repo or backports.
And i cannot update all my servers right now to Stretch.
Jessie is in LTS until the end of June 2020 so people will continue to use it for a year or so.

Could you please provide source code compatibility with 4.9 g++ ?

**Comment by Anaphase** [comment]
@apydo an alternative would be to use an argon2 version published _before_ the C++11 refactor. I'm not sure exactly what version that would be, but I know `0.12.0` builds on g++ 4.8. Not ideal, but it would let your builds actually build for now.

**Comment by apydo** [comment]
I already do that. As I stated in the bug report above, version 0.19.3 compiles fine.
However, I'm afraid I can't benefit of any new software version and bugfixes, if any, for a long time.

**Comment by ranisalt** [comment]
@apydo can you try branch `gcc48`?

**Comment by apydo** [comment]
I cloned, switched to gcc48 branch, made 'npm install' however it fails. Maybe it's not what I'm supposed to do ? Sorry, probably a newbie question.

```
apydo@n1:~/argon2/node-argon2$ npm install

> argon2@0.20.1 install /home/apydo/argon2/node-argon2
> node-gyp rebuild

make: Entering directory '/home/apydo/argon2/node-argon2/build'
make: *** No rule to make target 'Release/obj.target/libargon2/argon2/src/opt.o', needed by 'Release/obj.target/argon2.a'. Arrêt.
make: Leaving directory '/home/apydo/argon2/node-argon2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.16.0-7-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/apydo/argon2/node-argon2
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.20.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.20.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/apydo/.npm/_logs/2019-02-27T16_43_24_775Z-debug.log

```

**Comment by Anaphase** [comment]
@apydo you should be able to replace the existing argon2 in your project / package.json with this:

```bash
npm install --save ranisalt/node-argon2#gcc48
```

(You don't need to clone this repo or anything.)

**Comment by apydo** [comment]
Thanks a lot. It seems to work fine : 

```
$ npm install --save ranisalt/node-argon2#gcc48

> argon2@0.20.1 install /var/content/nodejs/lapv3dev/node_modules/argon2
> node-gyp rebuild

make: Entering directory '/var/content/nodejs/lapv3dev/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
  SOLINK_MODULE(target) Release/obj.target/argon2.node
  COPY Release/argon2.node
make: Leaving directory '/var/content/nodejs/lapv3dev/node_modules/argon2/build'
+ argon2@0.20.1
```

**Comment by apydo** [comment]
What's next ? Do you plan to merge gcc48 branch into master ?

**Comment by ranisalt** [comment]
> What's next ? Do you plan to merge gcc48 branch into master ?

Yes, and publish v0.21, doing that now...

**Comment by apydo** [comment]
Thanks a lot. Working fine on Debian Jessie and on Windows 10.
